### ISSUE TITLE
Playing option always shoy 5 points

### ISSUE THREAD

**Issue by NoNamedCat** [jcrona/tamatool#1]
Hello jcrona!
I have been playing with the emulator and i find that when the user plays with the tamagotchi at the end of the game it allways show 5 points to the player.

![image](https://user-images.githubusercontent.com/39467683/129043343-67427062-56df-4e47-be80-cd541c95a987.png)

**Comment by jcrona** [comment]
Indeed, I can reproduce the issue. However, it is not related to TamaTool since there is no emulation code there. If the issue comes from the emulator, it will be from [TamaLIB](https://github.com/jcrona/tamalib). I might also be an error in the ROM dump, I need investigate... Please open a new issue in the TamaLIB repository.
